config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'listings#new'
  resources :listings, only: %i[show create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/listing.rb
# frozen_string_literal: true

class Listing < ApplicationRecord
  MIN_RATING = 0
  MAX_RATING = 5

  attr_accessor :meta_keys

  validates :url, presence: true, uniqueness: true

  validates :price, numericality: { greater_than: 0, allow_nil: true, message: 'Price must be greater than 0' }
  validates :rating_value, numericality: { greater_than_or_equal_to: MIN_RATING, less_than_or_equal_to: MAX_RATING, allow_nil: true, message: 'Rating must be between 0 and 5' }
  validates :rating_count, numericality: { greater_than_or_equal_to: 0, allow_nil: true, message: 'Review count cannot be negative' }

  validate :validate_url

  def validate_url
    errors.add(:url, 'Invalid url') unless PublicSuffix.valid?(url) && url.start_with?('alza.cz/')
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include UrlHelper
end

app/controllers/listings_controller.rb
# frozen_string_literal: true

class ListingsController < ApplicationController
  class InvalidUrlError < StandardError; end

  def show
    @listing = Listing.find(params[:id])
    @filtered_meta_data = filter_meta_data(@listing.meta_data)
  end

  def new
    @listing = Listing.new
  end

  def create
    url = clean_url(listing_params[:url])
    raise InvalidUrlError, "URL must start with 'alza.cz/'" unless url.start_with?('alza.cz/')

    @listing = fetch_or_cache_listing(url)

    if @listing
      return redirect_to listing_url(@listing, meta_keys: listing_params[:meta_keys])
    end

    flash[:success] = 'Listing is being processed!'
    redirect_to root_path
  rescue StandardError => e
    @listing = Listing.new
    flash.now[:danger] = e.message
    render :new, status: :unprocessable_entity
  end

  private

  def listing_params
    params.require(:listing).permit(:url, :meta_keys)
  end

  def filter_meta_data(meta_data)
    meta_keys = parse_meta_keys

    meta_data.select { |key, _| meta_keys.include?(key) }
  end

  def fetch_or_cache_listing(url)
    Rails.cache.fetch(url, expires_in: 12.hours) do
      listing = Listing.find_or_initialize_by(url:)

      if listing.persisted?
        listing
      else
        ScrapListingDataJob.perform_later(url)
        nil
      end
    end
  end

  def parse_meta_keys
    params[:meta_keys]
      .to_s
      .split(',')
      .map(&:strip)
      .compact_blank
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/url_helper.rb
# frozen_string_literal: true

module UrlHelper
  def clean_url(url)
    parsed_url = URI.parse(url)
    parsed_url = URI.parse("http://#{url}") if parsed_url.scheme.nil?
    "#{parsed_url.host.sub(/^www\./, '')}#{parsed_url.path}"
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | b_scraper
    meta[name='viewport' content='width=device-width,initial-scale=1']
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
  body
    .container
      = render 'layouts/shared/flash'
    = yield

app/views/layouts/shared/_flash.html.slim
- if flash.any?
  - flash.each do |type, msg|
    .alert.alert-dissmissible.fade.show.d-flex.justify-content-between class="alert-#{type.to_s}"
      = msg
      button.btn-close[type="button" data-bs-dismiss="alert" aria-label="Close"]

app/views/layouts/shared/_nav.html.slim
.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom

app/views/listings/_form.html.slim
= simple_form_for listing, url: listings_path, method: :post do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :url, label: false, input_html: { class: 'form-control', placeholder: 'enter url' }, required: true

  .form-inputs
    = f.input :meta_keys, label: false, input_html: { class: 'form-control', placeholder: 'e.g. description, keywords' }

  .form-inputs.mb-4.mt-4
    = f.submit 'Submit', class: 'btn btn-primary'

app/views/listings/new.html.slim
.container.min-vh-100.d-flex.align-items-center.justify-content-center
  .w-100.p-4.border.shadow.bg-black.rounded-3.text-center[style="height: 360px;"]
    h1.display-4.text-white.mb-5.mt-4
      | B Scraper
    == render 'form', listing: @listing

app/views/listings/show.html.slim
.container.min-vh-100.d-flex.align-items-center.justify-content-center
  .card.shadow-lg.rounded-3.w-50
    .card-body
      h1.text-center.mb-4 Listing Details

      .mb-3
        strong URL:
        span.mb-0
          = " #{@listing.url}"

      .mb-3
        strong Price:
        span.mb-0.text-success
          = " #{@listing.price}"

      .mb-3
        strong Rating Value:
        span.mb-0
          = " #{@listing.rating_value}"

      .mb-3
        strong Rating Count:
        span.mb-0
          = " #{@listing.rating_count}"

      - if @filtered_meta_data.present?
        .mb-3
          strong Meta Data:
          ul
            - @filtered_meta_data.each do |key, value|
              li
                strong = "#{key.capitalize}: "
                span = value

      .text-center.mt-4
        = link_to 'Back', root_path, class: 'btn btn-secondary'